### ISSUE TITLE
[BUG] An inenarrable evaluate error happend from time to time.

### ISSUE THREAD

**Issue by zhanghaooo** [scikit-multiflow/scikit-multiflow#140]
**Describe the bug**
Hi, I run this simple example:
```
from skmultiflow.data import HyperplaneGenerator
from skmultiflow.trees import HoeffdingTree
from skmultiflow.evaluation import EvaluatePrequential

# 1. Create a stream
stream = HyperplaneGenerator()
stream.prepare_for_use()

# 2. Instantiate the HoeffdingTree classifier
ht = HoeffdingTree()

# 3. Setup the evaluator
evaluator = EvaluatePrequential(show_plot=True,
                                pretrain_size=200,
                                metrics=['f1'],
                                max_samples=20000)
# 4. Run evaluation
evaluator.evaluate(stream=stream, model=ht)
```
sometimes it runs successful, but it would fill sometimes:
```
Prequential Evaluation
Evaluating 1 target(s).
Pre-training on 200 sample(s).
Traceback (most recent call last):
  File "E:/PycharmProjects/sdoal/tem_test.py", line 19, in <module>
    evaluator.evaluate(stream=stream, model=ht)
  File "D:\Anaconda3\lib\site-packages\skmultiflow\evaluation\evaluate_prequential.py", line 250, in evaluate
    self.model = self._train_and_test()
  File "D:\Anaconda3\lib\site-packages\skmultiflow\evaluation\evaluate_prequential.py", line 375, in _train_and_test
    self.evaluation_summary()
  File "D:\Anaconda3\lib\site-packages\skmultiflow\evaluation\base_evaluator.py", line 625, in evaluation_summary
    self._data_buffer.get_data(metric_id=constants.F1_SCORE, data_id=constants.MEAN)[i]))
TypeError: 'NoneType' object is not subscriptable
Evaluating...
unsupported operand type(s) for -: 'int' and 'NoneType'
Processed samples: 201
Mean performance:

Process finished with exit code 1
```
I have no idea that why it will bahaving different sometimes..
Could anyone help me, thanks a lot.

**Comment by jacobmontiel** [comment]
Thanks for reporting this @zhanghaooo 

I can replicate the bug which as you mention is intermittent. I have found the likely root cause but need further tests. I will commit the fix asap.

**Comment by jacobmontiel** [comment]
The bug is triggered by the corner case where a given class has not been observed so no entry exists for it in the classification matrix (yet). The code for this scenario was not working correctly and I am uploading a fix for it. Also, I am setting the classification matrix by default to the binary case.

This fix will be available in the next release. In the meantime, a workaround is to set `pretrain_size` to a larger value (e.g. 1000) in order to improve the chances of observing all classes before the first performance evaluation.
