### ISSUE TITLE
 self.bucket_total[index] = value  ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by enassalehali** [scikit-multiflow/scikit-multiflow#146]
Hello every one
I executed the examples mentioned in adwin.py for jacob but with dataset first, I converted text data to list because an error occurred and the solution was to convert file.csv to list.After that, the following error is appeared
adwin.add_element(data[i])
IndexError: arrays used as indices must be of integer (or boolean) type
I solved the problem by change the instruction to adwin.add_element(data[i.astype('int64')])
finally, I encountered the following error
adwin.add_element(data[i.astype('int64')])
Traceback (most recent call last):
File "", line 2, in
adwin.add_element(data[i.astype('int64')])
File "C:\ProgramData\Anaconda3\lib\site-packages\skmultiflow\drift_detection\adwin.py", line 190, in add_element
self.__insert_element_bucket(0, value, self.list_row_bucket.first)
File "C:\ProgramData\Anaconda3\lib\site-packages\skmultiflow\drift_detection\adwin.py", line 202, in __insert_element_bucket
node.insert_bucket(value, variance)
File "C:\ProgramData\Anaconda3\lib\site-packages\skmultiflow\drift_detection\adwin.py", line 477, in insert_bucket
self.set_total(value, new_item)
File "C:\ProgramData\Anaconda3\lib\site-packages\skmultiflow\drift_detection\adwin.py", line 512, in set_total
self.bucket_total[index] = value
ValueError: setting an array element with a sequence.
_______________________
help please !!!

**Comment by enassalehali** [comment]
Hello every one 
I executed the examples mentioned in adwin.py for jacob but with dataset first, I converted text data to list because an error occurred and the solution was to convert file.csv to list.After that, the following error is appeared 
 adwin.add_element(data[i])
IndexError: arrays used as indices must be of integer (or boolean) type
I solved the problem by change the instruction to  adwin.add_element(data[i.astype('int64')])
finally, I encountered the following error 
adwin.add_element(data[i.astype('int64')])
Traceback (most recent call last):
  File "<ipython-input-27-d91573f82e4d>", line 2, in <module>
    adwin.add_element(data[i.astype('int64')])
  File "C:\ProgramData\Anaconda3\lib\site-packages\skmultiflow\drift_detection\adwin.py", line 190, in add_element
   self.__insert_element_bucket(0, value, self.list_row_bucket.first)
  File "C:\ProgramData\Anaconda3\lib\site-packages\skmultiflow\drift_detection\adwin.py", line 202, in __insert_element_bucket
    node.insert_bucket(value, variance)
  File "C:\ProgramData\Anaconda3\lib\site-packages\skmultiflow\drift_detection\adwin.py", line 477, in insert_bucket
    self.set_total(value, new_item)
  File "C:\ProgramData\Anaconda3\lib\site-packages\skmultiflow\drift_detection\adwin.py", line 512, in set_total
    self.bucket_total[index] = value
ValueError: setting an array element with a sequence.
  _________________
help please ?

**Comment by jacobmontiel** [comment]
The [`add_element` method](https://scikit-multiflow.github.io/scikit-multiflow/_autosummary/skmultiflow.drift_detection.ADWIN.html#skmultiflow.drift_detection.ADWIN.add_element) does not take arrays as inputs, only single values (int or float). This is why you are seeing this (expected) error.

**Comment by enassalehali** [comment]
Really!!
So,How can I work with real data sets that contain  rows and attributes?


regards,

**Comment by jacobmontiel** [comment]
Closing, no action required.
