### ISSUE TITLE
[BUG] setup.py error on python 2.7.x

### ISSUE THREAD

**Issue by nuwangunasekara** [scikit-multiflow/scikit-multiflow#185]
**Description**
I came across below error by mistake when following instructions in 
https://github.com/scikit-multiflow/scikit-multiflow/blob/master/CONTRIBUTING.md:
```
pip install -e .
Obtaining file:///home/nuwan/Desktop/scikit-multiflow
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/nuwan/Desktop/scikit-multiflow/setup.py", line 12, in <module>
        " Python version is {} installed in {}}.".format(platform.python_version(), sys.executable))
    ValueError: Single '}' encountered in format string
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/nuwan/Desktop/scikit-multiflow/
```

Removed the extra '}' at line 12, and the setup failed with the appropriate error:
```
pip install -e .
Obtaining file:///home/nuwan/Desktop/scikit-multiflow
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/nuwan/Desktop/scikit-multiflow/setup.py", line 12, in <module>
        " Python version is {} installed in {}.".format(platform.python_version(), sys.executable))
    RuntimeError: scikit-multiflow requires Python 3.5 or later. The current Python version is 2.7.17 installed in /usr/bin/python.
```
**To Reproduce**
run setup.py with python 2.7.x

**Expected behavior**
Early termination without script failure. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by smastelini** [comment]
Hi @nuwangunasekara. As described on the installation instructions, skmultiflow works with Python 3.5+ only. You can check that either on the following line of your error log:

`RuntimeError: scikit-multiflow requires Python 3.5 or later. The current Python version is 2.7.17 installed in /usr/bin/python.`

I suggest you change your current python setup for a newer version. If you are running a Linux distribution, you can simply change the `python` command to `python3`. This should make everything work as intended. You can find detailed information on installing skmultiflow in the [documentation](https://scikit-multiflow.github.io/scikit-multiflow/installation.html) page.

**Comment by nuwangunasekara** [comment]
Hi @smastelini,
Thanks for the reply!

It looks like the setup.py yields below **syntax error** if ones /usr/bin/python is linked to python 2.7 binary:
```
pip install -e .
Obtaining file:///home/nuwan/Desktop/scikit-multiflow
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/nuwan/Desktop/scikit-multiflow/setup.py", line 12, in <module>
        " Python version is {} installed in {}}.".format(platform.python_version(), sys.executable))
    ValueError: Single '}' encountered in format string
```
instead of the expected:
```
RuntimeError: scikit-multiflow requires Python 3.5 or later. The current Python version is 2.7.17 installed in /usr/bin/python.
```
error message. 

I think this is a very minor issue. Just raised a ticket as I came across the same.

**Comment by jacobmontiel** [comment]
That is a fair point. A graceful termination is desirable.
