### ISSUE TITLE
HoeffdingTree classifier fails with spam dataset

### ISSUE THREAD

**Issue by nuwangunasekara** [scikit-multiflow/scikit-multiflow#257]
[bug_info.zip](https://github.com/scikit-multiflow/scikit-multiflow/files/4810419/bug_info.zip)

```
(base) nuwan@nuwan-asus:~/Desktop/scikit-multiflow$ git reflog 
495659aa (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: pull origin master: Fast-forward
b0d4bd1a HEAD@{1}: reset: moving to HEAD
b0d4bd1a HEAD@{2}: reset: moving to HEAD
b0d4bd1a HEAD@{3}: clone: from https://github.com/scikit-multiflow/scikit-multiflow.git

(base) nuwan@nuwan-asus:~/Desktop/scikit-multiflow$ source venv/bin/activate

(venv) (base) nuwan@nuwan-asus:~/Desktop/scikit-multiflow$ venv/bin/python test.py -i ~/Desktop/spam_corpus_class_map_100.csv -o /dev/null
Input dimensions = 39916
/home/nuwan/Desktop/scikit-multiflow/src/skmultiflow/trees/hoeffding_tree.py:35: FutureWarning: 'HoeffdingTree' has been renamed to 'HoeffdingTreeClassifier' in v0.5.0.
The old name will be removed in v0.7.0
  "The old name will be removed in v0.7.0", category=FutureWarning)
[HoeffdingTreeClassifier(binary_split=False, grace_period=200,
                        leaf_prediction='nba', max_byte_size=33554432,
                        memory_estimate_period=1000000, nb_threshold=0,
                        no_preprune=False, nominal_attributes=None,
                        remove_poor_atts=False, split_confidence=1e-07,
                        split_criterion='info_gain', stop_mem_management=False,
                        tie_threshold=0.05)]
['HT']
Prequential Evaluation
Evaluating 1 target(s).
Evaluating...
 ######-------------- [28%] [20.30s]/home/nuwan/Desktop/scikit-multiflow/src/skmultiflow/bayes/utils.py:37: RuntimeWarning: overflow encountered in double_scalars
  X[att_idx], class_index)
/home/nuwan/Desktop/scikit-multiflow/src/skmultiflow/utils/utils.py:62: RuntimeWarning: invalid value encountered in double_scalars
  dictionary[key] = value / factor
 ##########---------- [48%] [35.24s]/home/nuwan/Desktop/scikit-multiflow/src/skmultiflow/bayes/utils.py:37: RuntimeWarning: invalid value encountered in double_scalars
  X[att_idx], class_index)
Can not normalize, normalization factor is NaN
Processed samples: 50
Mean performance:
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    evaluator.evaluate(stream=stream, model=learner, model_names=learner_name)
  File "/home/nuwan/Desktop/scikit-multiflow/src/skmultiflow/evaluation/evaluate_prequential.py", line 250, in evaluate
    self.model = self._train_and_test()
  File "/home/nuwan/Desktop/scikit-multiflow/src/skmultiflow/evaluation/evaluate_prequential.py", line 375, in _train_and_test
    self.evaluation_summary()
  File "/home/nuwan/Desktop/scikit-multiflow/src/skmultiflow/evaluation/base_evaluator.py", line 612, in evaluation_summary
    self._data_buffer.get_data(metric_id=constants.ACCURACY, data_id=constants.MEAN)[i]))
TypeError: 'NoneType' object is not subscriptable

```

Attached is the test scrip and first 99 instances of spam dataset.

I used get_data_set_info.py to check whether spam_corpus_class_map_100.csv has any missing values. But it does not seem to have any:
```
(venv) (base) nuwan@nuwan-asus:~/Desktop/scikit-multiflow$ venv/bin/python get_data_set_info.py -i ~/Desktop/spam_corpus_class_map_100.csv
columns with missing values:  Index([], dtype='object')
```

**Comment by jacobmontiel** [comment]
Thanks for reporting this @nuwangunasekara

It seems that the culprit is an underflow/overflow in the calculation of probability calculation for naive Bayes:

https://github.com/scikit-multiflow/scikit-multiflow/blob/495659aa235a7b6464c80d5b83528129829418a9/src/skmultiflow/bayes/utils.py#L36-L37

At some point, the calculation returns a `NaN` which ends in the votes and eventually triggers an error. This is likely related to the high dimensionality of the dataset (+39.9K attributes).

Here is a suggestion to protect the calculation:

```python
                    tmp = votes[class_index] * obs.probability_of_attribute_value_given_class(
                        X[att_idx], class_index)
                    votes[class_index] = tmp if not np.isnan(tmp) else 0
```

Comments @smastelini

**Comment by smastelini** [comment]
Thanks for reporting the problem @nuwangunasekara.

The workaround looks good to me, @jacobmontiel. What about using `math.isnan` rather than the numpy function? We might get some slight performance improvements.

**Comment by jacobmontiel** [comment]
> What about using math.isnan rather than the numpy function?

Agree, the calculations in `probability_of_attribute_value_given_class` are performed using the `math` package anyway.

**Comment by smastelini** [comment]
Closing since it was adressed in #258.
